[pytest]
# Directorios donde pytest buscará pruebas
testpaths = tests

# Patrones para encontrar archivos de prueba
python_files = test_*.py *_test.py

# Patrones para encontrar clases de prueba
python_classes = Test*

# Patrones para encontrar funciones de prueba
python_functions = test_*

# Argumentos por defecto (ej: -v para verbose, -s para ver prints)
addopts = -v --strict-markers